# Generated by Django 5.0.6 on 2025-02-10 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=8)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='InfoInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True)),
                ('status_instrumento', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('em_uso', 'Em uso'), ('desuso', 'Desuso'), ('danificado', 'Danificado')], default='ativo', max_length=10)),
                ('tempo_calibracao', models.IntegerField(help_text='Tempo entre uma calibração e outra (em dias)')),
                ('ultima_calibracao', models.DateField()),
                ('proxima_calibracao', models.DateField(blank=True, null=True)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
            ],
            options={
                'verbose_name': 'Informação do Instrumento',
                'verbose_name_plural': 'Informações dos Instrumentos',
                'ordering': ['tipo_instrumento'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Operadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=8)),
            ],
            options={
                'verbose_name': 'Operadores',
                'verbose_name_plural': 'Operadoress',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DesignarInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega_funcionario', models.DateField()),
                ('pdf', models.URLField(blank=True, null=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.funcionario')),
                ('instrumento_escolhido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designar_instrumento', to='cadastro.infoinstrumento')),
            ],
            options={
                'verbose_name': 'Designação de Instrumento',
                'verbose_name_plural': 'Designações de Instrumentos',
                'ordering': ['instrumento_escolhido'],
            },
        ),
        migrations.AddField(
            model_name='infoinstrumento',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.marca'),
        ),
        migrations.CreateModel(
            name='PontoCalibracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('faixa_nominal', models.CharField(max_length=50)),
                ('unidade', models.CharField(max_length=20)),
                ('tolerancia_admissivel', models.FloatField(blank=True, null=True)),
                ('status_ponto_calibracao', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_calibracao', to='cadastro.infoinstrumento')),
            ],
            options={
                'verbose_name': 'Ponto de Calibração',
                'verbose_name_plural': 'Pontos de Calibração',
            },
        ),
        migrations.CreateModel(
            name='HistoricoInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mudanca', models.CharField(choices=[('enviado', 'Enviado'), ('recebido', 'Recebido'), ('analisado', 'Analisado'), ('troca_reponsavel', 'Troca de responsável'), ('atribuicao', 'Atribuição'), ('danificado', 'Danificado'), ('devolvido', 'Devolvido')], help_text='Tipo da mudança ocorrida (ex: enviado, recebido, analisado).', max_length=50)),
                ('data_mudanca', models.DateTimeField(auto_now_add=True)),
                ('descricao_mudanca', models.TextField(blank=True, null=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='cadastro.infoinstrumento')),
                ('ponto_calibracao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ponto_calibracao_historico', to='cadastro.pontocalibracao')),
            ],
            options={
                'verbose_name': 'Histórico de Instrumento',
                'verbose_name_plural': 'Históricos de Instrumentos',
                'ordering': ['-data_mudanca'],
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.setor'),
        ),
        migrations.AddField(
            model_name='infoinstrumento',
            name='tipo_instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_instrumento', to='cadastro.tipoinstrumento'),
        ),
    ]
