# Generated by Django 4.2.15 on 2024-09-02 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=20)),
            ],
            options={
                'verbose_name': 'Laboratório',
                'verbose_name_plural': 'Laboratórios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InfoInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('status_instrumento', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('em_uso', 'Em uso'), ('desuso', 'Desuso'), ('danificado', 'Danificado')], default='ativo', max_length=10)),
                ('tempo_calibracao', models.IntegerField(help_text='Tempo entre uma calibração e outra (em dias)')),
                ('status_calibracao', models.CharField(blank=True, choices=[('atrasado', 'Atrasado'), ('em dia', 'Em dia'), ('enviado', 'Enviado')], max_length=20, null=True)),
                ('ultima_calibracao', models.DateField()),
                ('proxima_calibracao', models.DateField(blank=True, null=True)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.marca')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.unidade')),
            ],
            options={
                'verbose_name': 'Informação do Instrumento',
                'verbose_name_plural': 'Informações dos Instrumentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=8)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.setor')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DesignarInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega_funcionario', models.DateField()),
                ('instrumento_escolhido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designar_instrumento', to='cadastro.infoinstrumento')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.funcionario')),
            ],
            options={
                'verbose_name': 'Designação de Instrumento',
                'verbose_name_plural': 'Designações de Instrumentos',
                'ordering': ['instrumento_escolhido'],
            },
        ),
    ]
