# Generated by Django 4.2.15 on 2024-09-02 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='infoinstrumento',
            options={'ordering': ['tipo_instrumento'], 'verbose_name': 'Informação do Instrumento', 'verbose_name_plural': 'Informações dos Instrumentos'},
        ),
        migrations.RemoveField(
            model_name='infoinstrumento',
            name='nome',
        ),
        migrations.AddField(
            model_name='infoinstrumento',
            name='faixa_nominal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='infoinstrumento',
            name='tipo_instrumento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_instrumento', to='cadastro.tipoinstrumento'),
            preserve_default=False,
        ),
    ]
