# Generated by Django 5.0.6 on 2025-06-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontocalibracao',
            name='unidade',
            field=models.CharField(blank=True, default='-', max_length=20, null=True),
        ),
    ]
