# Generated by Django 4.2.26 on 2025-11-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_pontocalibracao_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoinstrumento',
            name='necessita_calibrar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicoinstrumento',
            name='tipo_mudanca',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('recebido', 'Recebido'), ('analisado', 'Analisado'), ('troca_reponsavel', 'Troca de responsável'), ('atribuicao', 'Atribuição'), ('danificado', 'Danificado'), ('devolvido', 'Devolvido'), ('link_modificado', 'Link Modificado')], help_text='Tipo da mudança ocorrida (ex: enviado, recebido, analisado).', max_length=50),
        ),
    ]
