# Generated by Django 4.2.15 on 2024-09-02 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro', '0002_tipoinstrumento_alter_infoinstrumento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designarinstrumento',
            options={},
        ),
        migrations.CreateModel(
            name='HistoricoInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_mudanca', models.DateTimeField(auto_now_add=True)),
                ('descricao_mudanca', models.TextField(blank=True, null=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='cadastro.infoinstrumento')),
                ('responsavel_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_responsavel_anterior', to=settings.AUTH_USER_MODEL)),
                ('responsavel_novo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_responsavel_novo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Instrumento',
                'verbose_name_plural': 'Históricos de Instrumentos',
                'ordering': ['-data_mudanca'],
            },
        ),
    ]
