# Generated by Django 4.2.15 on 2024-09-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_designarinstrumento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designarinstrumento',
            options={'ordering': ['instrumento_escolhido'], 'verbose_name': 'Designação de Instrumento', 'verbose_name_plural': 'Designações de Instrumentos'},
        ),
        migrations.RemoveField(
            model_name='infoinstrumento',
            name='status_calibracao',
        ),
        migrations.AddField(
            model_name='infoinstrumento',
            name='tolerancia_admissivel',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
