# Generated by Django 4.2.15 on 2024-12-05 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0004_alter_envio_laboratorio'),
        ('cadastro', '0004_alter_designarinstrumento_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laboratorio',
        ),
        migrations.AlterField(
            model_name='historicoinstrumento',
            name='responsavel_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_responsavel_anterior', to='cadastro.funcionario'),
        ),
        migrations.AlterField(
            model_name='historicoinstrumento',
            name='responsavel_novo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_responsavel_novo', to='cadastro.funcionario'),
        ),
    ]
