# Generated by Django 4.2.15 on 2024-12-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_delete_laboratorio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=8)),
            ],
            options={
                'verbose_name': 'Operadores',
                'verbose_name_plural': 'Operadoress',
                'ordering': ['nome'],
            },
        ),
    ]
