# Generated by Django 4.2.15 on 2024-12-09 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_operadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoinstrumento',
            name='faixa_nominal',
        ),
        migrations.RemoveField(
            model_name='infoinstrumento',
            name='tolerancia_admissivel',
        ),
        migrations.CreateModel(
            name='PontoCalibracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa_nominal', models.CharField(max_length=50)),
                ('unidade', models.CharField(max_length=20)),
                ('tolerancia_admissivel', models.FloatField(blank=True, null=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_calibracao', to='cadastro.infoinstrumento')),
            ],
            options={
                'verbose_name': 'Ponto de Calibração',
                'verbose_name_plural': 'Pontos de Calibração',
            },
        ),
    ]
