# Generated by Django 4.2.15 on 2024-12-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_pontocalibracao_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoinstrumento',
            name='unidade',
        ),
    ]
