# Generated by Django 4.2.15 on 2024-12-09 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_remove_infoinstrumento_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoinstrumento',
            name='ponto_calibracao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ponto_calibracao_historico', to='cadastro.pontocalibracao'),
            preserve_default=False,
        ),
    ]
