# Generated by Django 4.2.15 on 2024-12-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_historicoinstrumento_ponto_calibracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoinstrumento',
            name='responsavel_anterior',
        ),
        migrations.RemoveField(
            model_name='historicoinstrumento',
            name='responsavel_novo',
        ),
    ]
