# Generated by Django 4.2.15 on 2024-12-09 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_historicoinstrumento_tipo_mudanca'),
    ]

    operations = [
        migrations.AddField(
            model_name='designarinstrumento',
            name='pdf',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicoinstrumento',
            name='ponto_calibracao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ponto_calibracao_historico', to='cadastro.pontocalibracao'),
        ),
    ]
