# Generated by Django 5.0.6 on 2025-01-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_assinaturainstrumento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssinaturaInstrumento',
        ),
    ]
