# Generated by Django 5.0.6 on 2025-02-10 14:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assinatura', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('foto_assinatura', models.ImageField(blank=True, null=True, upload_to='assinaturas_fotos/')),
                ('motivo', models.CharField(choices=[('entrega', 'Entrega')], max_length=30)),
                ('assinante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.funcionario')),
                ('instrumento', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='assinatura_instrumento', to='cadastro.infoinstrumento')),
            ],
            options={
                'verbose_name': 'Assinatura de Instrumento',
                'verbose_name_plural': 'Assinaturas de Instrumentos',
                'ordering': ['-data_assinatura'],
            },
        ),
        migrations.CreateModel(
            name='StatusInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('substituição', 'Substituição'), ('devolução', 'Devolução')], max_length=15)),
                ('data_entrega', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais', null=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.funcionario')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrega_instrumento', to='cadastro.infoinstrumento')),
            ],
            options={
                'verbose_name': 'Status do Instrumento',
                'verbose_name_plural': 'Status dos Instrumentos',
            },
        ),
    ]
