# Generated by Django 5.0.6 on 2025-01-11 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0016_delete_assinaturainstrumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assinatura', models.DateTimeField(auto_now_add=True)),
                ('foto_assinatura', models.ImageField(blank=True, null=True, upload_to='assinaturas_fotos/')),
                ('assinante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.funcionario')),
                ('designacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='cadastro.designarinstrumento')),
            ],
            options={
                'verbose_name': 'Assinatura de Instrumento',
                'verbose_name_plural': 'Assinaturas de Instrumentos',
                'ordering': ['-data_assinatura'],
            },
        ),
    ]
