# Generated by Django 5.0.6 on 2025-01-14 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_delete_assinaturainstrumento'),
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinaturainstrumento',
            name='designacao',
        ),
        migrations.AddField(
            model_name='assinaturainstrumento',
            name='instrumento_escolhido',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='assinatura_instrumento', to='cadastro.infoinstrumento'),
        ),
    ]
