# Generated by Django 5.0.6 on 2025-01-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_remove_assinaturainstrumento_designacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assinaturainstrumento',
            old_name='instrumento_escolhido',
            new_name='instrumento',
        ),
    ]
