# Generated by Django 5.0.6 on 2025-01-14 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0004_assinaturainstrumento_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturainstrumento',
            name='data_entrega',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 14, 18, 2, 9, 783182)),
        ),
    ]
