# Generated by Django 5.0.6 on 2025-01-14 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0005_assinaturainstrumento_data_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinaturainstrumento',
            name='data_entrega',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
