# Generated by Django 5.0.6 on 2025-01-15 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_delete_assinaturainstrumento'),
        ('ficha', '0006_alter_assinaturainstrumento_data_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('substituição', 'Substituição'), ('devolução', 'Devolução')], max_length=15)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.funcionario')),
                ('info_instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrega_instrumento', to='cadastro.infoinstrumento')),
            ],
            options={
                'verbose_name': 'Status do Instrumento',
                'verbose_name_plural': 'Status dos Instrumentos',
            },
        ),
    ]
