# Generated by Django 5.0.6 on 2025-01-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0007_statusinstrumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinaturainstrumento',
            name='motivo',
            field=models.CharField(choices=[('primeira entrega', 'Primeira Entrega')], max_length=30),
        ),
    ]
