# Generated by Django 5.0.6 on 2025-01-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0008_alter_assinaturainstrumento_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusinstrumento',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações adicionais', null=True),
        ),
    ]
