# Generated by Django 5.0.6 on 2025-01-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0009_statusinstrumento_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinaturainstrumento',
            name='motivo',
            field=models.CharField(choices=[('entrega', 'Entrega')], max_length=30),
        ),
    ]
