# Generated by Django 5.0.6 on 2025-01-16 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0010_alter_assinaturainstrumento_motivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusinstrumento',
            name='data_atualizacao',
        ),
        migrations.AddField(
            model_name='statusinstrumento',
            name='data_entrega',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
