# Generated by Django 5.0.6 on 2025-01-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0011_remove_statusinstrumento_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusinstrumento',
            old_name='info_instrumento',
            new_name='instrumento',
        ),
    ]
