# Generated by Django 5.0.6 on 2025-01-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0012_rename_info_instrumento_statusinstrumento_instrumento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusinstrumento',
            old_name='status',
            new_name='motivo',
        ),
    ]
