# Generated by Django 5.0.6 on 2025-02-10 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=20)),
            ],
            options={
                'verbose_name': 'Laboratório',
                'verbose_name_plural': 'Laboratórios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateField(blank=True, null=True)),
                ('data_retorno', models.DateField(blank=True, null=True)),
                ('natureza', models.CharField(choices=[('verificacao', 'Verificação'), ('calibracao', 'Calibração')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('enviado', 'Enviado'), ('recebido', 'Recebido')], max_length=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('pdf', models.URLField(blank=True, null=True)),
                ('metodo', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], max_length=20)),
                ('analise', models.BooleanField(default=False, null=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='cadastro.infoinstrumento')),
                ('ponto_calibracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponto', to='cadastro.pontocalibracao')),
                ('responsavel_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_envio', to='cadastro.operadores')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspecao.laboratorio')),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envios',
                'ordering': ['data_envio'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analise_certificado', models.CharField(blank=True, choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], max_length=20, null=True)),
                ('incerteza', models.FloatField(blank=True, null=True)),
                ('tendencia', models.FloatField(blank=True, null=True)),
                ('data_analise', models.DateField(blank=True, null=True)),
                ('responsavel_analise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_analise', to='cadastro.operadores')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analise_envio', to='inspecao.envio')),
            ],
        ),
    ]
