# Generated by Django 4.2.15 on 2024-09-02 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateField(blank=True, null=True)),
                ('data_retorno', models.DateField(blank=True, null=True)),
                ('natureza', models.CharField(choices=[('verificacao', 'Verificação'), ('calibracao', 'Calibração')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('enviado', 'Enviado'), ('recebido', 'Recebido')], max_length=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('analise_certificado', models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], max_length=20)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('metodo', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], max_length=20)),
                ('tendencia', models.FloatField()),
                ('incerteza', models.FloatField()),
                ('data_analise', models.DateField()),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='cadastro.infoinstrumento')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.laboratorio')),
                ('responsavel_analise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_analise', to=settings.AUTH_USER_MODEL)),
                ('responsavel_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_envio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envios',
                'ordering': ['data_envio'],
            },
        ),
    ]
