# Generated by Django 5.0.6 on 2025-02-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=10, unique=True)),
                ('data_lancamento', models.DateField()),
                ('tipo', models.CharField(choices=[('bug', 'Bug'), ('funcionalidade', 'Funcionalidade'), ('implementacao', 'Implementação')], max_length=20)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
