# Generated by Django 4.2.15 on 2024-12-05 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0003_laboratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspecao.laboratorio'),
        ),
    ]
