# Generated by Django 4.2.15 on 2024-12-05 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_delete_laboratorio_and_more'),
        ('inspecao', '0005_remove_envio_analise_certificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='responsavel_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_envio', to='cadastro.funcionario'),
        ),
    ]
