# Generated by Django 4.2.15 on 2024-12-05 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_operadores'),
        ('inspecao', '0006_alter_envio_responsavel_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='responsavel_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_envio', to='cadastro.operadores'),
        ),
    ]
