# Generated by Django 4.2.15 on 2024-12-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0007_alter_envio_responsavel_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='pdf',
            field=models.URLField(blank=True, null=True),
        ),
    ]
