# Generated by Django 4.2.15 on 2024-12-06 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_operadores'),
        ('inspecao', '0009_envio_analise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisecertificado',
            name='responsavel_analise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_analise', to='cadastro.operadores'),
        ),
    ]
